name: CI

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Start DevContainer
        uses: devcontainer-env/devcontainer-ci@v1

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Run Tests
        run: nix develop --command go tool ginkgo run -r

  release:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create Release PR
        id: release
        uses: googleapis/release-please-action@v4
        with:
          manifest-file: .github/config/release-please-manifest.json
          config-file: .github/config/release-please-config.json
          target-branch: main
