name: Auto Merge

on:
  pull_request:

permissions: write-all

jobs:
  automerge:
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: actions/github-script@v9.0.0
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.rest.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: "rebase",
            })
          github-token: ${{ github.token }}
