name: Auto Merge

on:
  pull_request:
    types: [opened, reopened]

defaults:
  run:
    shell: bash

jobs:
  merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 5
    steps:
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr review --approve --body "LGTM" "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
